/**
 * Post-process svelte-package output to make the package fully
 * self-contained styling-wise.
 *
 * What this does:
 *   1. For each .svelte file in dist/, extract <style> blocks,
 *      preprocess @apply via PostCSS + Tailwind, and collect the
 *      resulting raw CSS.
 *   2. Strip <style> blocks from the .svelte files (replace with
 *      empty <style></style>) so the Svelte compiler doesn't emit
 *      per-component CSS that might conflict with editor.css.
 *   3. Append the collected CSS to dist/editor.css (which already
 *      contains utility classes from build:css).
 *   4. Scope ALL rules in editor.css under .rich-text-editor-container
 *      so utility classes like .flex, .hidden, .relative don't leak
 *      into the consumer's app and clobber their own styles.
 *
 * Why: Tailwind's content scanner ignores node_modules (via
 * .gitignore), so inline utility classes in templates are not
 * generated by the consumer's Tailwind build. Also, @apply in
 * <style> blocks may not be processed in Vite dev mode for
 * .svelte files from node_modules. Shipping one self-contained,
 * scoped editor.css that the consumer imports once solves all
 * problems without requiring any Tailwind/PostCSS configuration.
 *
 * Consumer just does:  import 'svelte-wysiwyg-editor/editor.css';
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'fs';
import { join, extname } from 'path';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = resolve(__dirname, '..');
const DIST_DIR = join(PROJECT_ROOT, 'dist');
const EDITOR_CSS = join(DIST_DIR, 'editor.css');
const SCOPE_SELECTOR = '.rich-text-editor-container';

/**
 * PostCSS plugin that prefixes all rule selectors with SCOPE_SELECTOR,
 * unless the rule is inside @keyframes or already contains the scope.
 */
const scopePlugin = {
  postcssPlugin: 'scope-to-editor',
  Rule(rule) {
    // Skip rules inside @keyframes — they're keyframe percentages, not selectors
    let parent = rule.parent;
    while (parent) {
      if (parent.type === 'atrule' && parent.name === 'keyframes') return;
      parent = parent.parent;
    }

    // Skip if already scoped
    if (rule.selector.includes(SCOPE_SELECTOR)) return;

    // Prefix each comma-separated selector
    rule.selectors = rule.selectors.map((sel) => {
      // Don't prefix bare pseudo-elements or empty selectors
      if (!sel.trim()) return sel;
      return `${SCOPE_SELECTOR} ${sel}`;
    });
  },
};

function findSvelteFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...findSvelteFiles(fullPath));
    } else if (extname(fullPath) === '.svelte') {
      files.push(fullPath);
    }
  }
  return files;
}

async function processFile(filePath) {
  let content = readFileSync(filePath, 'utf-8');
  const styleRegex = /<style(\s[^>]*)?>([\s\S]*?)<\/style>/g;
  const matches = [...content.matchAll(styleRegex)];
  if (matches.length === 0) return '';

  let collectedCss = '';

  for (const match of matches) {
    const [fullMatch, attrs, cssContent] = match;
    if (!cssContent.trim()) continue;

    // Preprocess @apply (and any other Tailwind/PostCSS features)
    const processed = await postcss([
      tailwindcss({ config: join(PROJECT_ROOT, 'tailwind.config.js') }),
      autoprefixer,
    ]).process(cssContent, { from: undefined });

    collectedCss += '\n/* ' + filePath.replace(DIST_DIR, '') + ' */\n' + processed.css;
  }

  // Strip all <style> blocks — replace with empty block to keep
  // Svelte compiler happy (it expects a valid .svelte file).
  content = content.replace(styleRegex, '<style></style>');
  writeFileSync(filePath, content, 'utf-8');
  console.log('  stripped+collected:', filePath.replace(DIST_DIR, ''));
  return collectedCss;
}

async function main() {
  console.log('Collecting & preprocessing <style> blocks from dist/ .svelte files...');
  const files = findSvelteFiles(DIST_DIR);
  let allCss = '';
  for (const file of files) {
    allCss += await processFile(file);
  }

  // Append collected component CSS to editor.css (which already
  // contains utility classes from the prior build:css step).
  if (allCss.trim()) {
    const existing = existsSync(EDITOR_CSS) ? readFileSync(EDITOR_CSS, 'utf-8') : '';
    writeFileSync(EDITOR_CSS, existing + '\n/* === Component <style> blocks === */\n' + allCss, 'utf-8');
    console.log('Appended component CSS to', EDITOR_CSS.replace(PROJECT_ROOT, ''));
  }

  // Scope ALL rules in editor.css under .rich-text-editor-container
  // so that utility classes (.flex, .hidden, .relative, etc.) don't
  // leak into the consumer's app and clobber their own styles.
  console.log('Scoping all selectors to', SCOPE_SELECTOR, '...');
  const finalCss = readFileSync(EDITOR_CSS, 'utf-8');
  const scoped = await postcss([scopePlugin]).process(finalCss, { from: undefined });
  writeFileSync(EDITOR_CSS, scoped.css, 'utf-8');
  console.log('Scoped editor.css written.');

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
