/**
 * Post-process svelte-package output to make the package fully
 * self-contained styling-wise.
 *
 * What this does:
 *   1. For each .svelte file in dist/, extract <style> blocks,
 *      preprocess @apply via PostCSS + Tailwind into raw CSS,
 *      and write the processed CSS back into the <style> block.
 *      The Svelte compiler in the consumer's project will then
 *      compile these <style> blocks and add per-component hashes
 *      to the class names, preventing conflicts between components
 *      that share class names (e.g. .popover in ColorPicker vs
 *      EditorToolbar).
 *   2. Collect utility classes from all .svelte templates and
 *      compile them into dist/editor.css (via build:css step).
 *   3. Scope ALL utility-class rules in editor.css under
 *      .rich-text-editor-container so they don't leak into the
 *      consumer's app.
 *
 * Why: Tailwind's content scanner ignores node_modules (via
 * .gitignore), so inline utility classes in templates are not
 * generated by the consumer's Tailwind build. @apply in <style>
 * blocks may not be processed in Vite dev mode for .svelte files
 * from node_modules. By preprocessing @apply into raw CSS and
 * keeping <style> blocks in the .svelte files, the consumer's
 * Svelte compiler handles hashing (no class name conflicts) while
 * editor.css provides the utility classes (scoped to the editor
 * container).
 *
 * Consumer just does:  import 'svelte-wysiwyg-editor/editor.css';
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'fs';
import { join, extname } from 'path';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = resolve(__dirname, '..');
const DIST_DIR = join(PROJECT_ROOT, 'dist');
const EDITOR_CSS = join(DIST_DIR, 'editor.css');
const SCOPE_SELECTOR = '.rich-text-editor-container';

/**
 * PostCSS plugin that converts Tailwind's `:is(.dark *)` selectors
 * to Svelte's `:global(.dark)` syntax so the Svelte compiler doesn't
 * mangle them.
 *
 * Tailwind v3.4+ with darkMode:'class' generates:
 *   .foo:is(.dark *) { ... }
 *
 * Svelte's compiler tries to add its hash inside :is(), producing:
 *   :is(.dark:where(.svelte-hash) :where(.svelte-hash)) { ... }
 * which is broken and never matches.
 *
 * This plugin transforms:
 *   .foo:is(.dark *)           → :global(.dark) .foo
 *   .foo:hover:is(.dark *)     → :global(.dark) .foo:hover
 *   .foo.active:is(.dark *)    → :global(.dark) .foo.active
 *
 * Svelte correctly handles :global() — it won't add hashes to the
 * part inside :global(), only to the rest of the selector.
 */
const fixDarkModePlugin = {
  postcssPlugin: 'fix-dark-mode-for-svelte',
  Rule(rule) {
    if (!rule.selector.includes(':is(.dark')) return;

    rule.selectors = rule.selectors.map((sel) => {
      // Pattern: <base>:is(.dark *)<rest>
      // Replace with: :global(.dark) <base><rest>
      const match = sel.match(/^(.+?):is\(\.dark \*\)(.*)$/);
      if (match) {
        return `:global(.dark) ${match[1]}${match[2]}`;
      }
      return sel;
    });
  },
};

/**
 * PostCSS plugin that prefixes all rule selectors with SCOPE_SELECTOR,
 * unless the rule is inside @keyframes or already contains the scope.
 */
const scopePlugin = {
  postcssPlugin: 'scope-to-editor',
  Rule(rule) {
    // Skip rules inside @keyframes — they're keyframe percentages, not selectors
    let parent = rule.parent;
    while (parent) {
      if (parent.type === 'atrule' && parent.name === 'keyframes') return;
      parent = parent.parent;
    }

    // Skip if already scoped
    if (rule.selector.includes(SCOPE_SELECTOR)) return;

    // Prefix each comma-separated selector
    rule.selectors = rule.selectors.map((sel) => {
      // Don't prefix bare pseudo-elements or empty selectors
      if (!sel.trim()) return sel;
      return `${SCOPE_SELECTOR} ${sel}`;
    });
  },
};

function findSvelteFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...findSvelteFiles(fullPath));
    } else if (extname(fullPath) === '.svelte') {
      files.push(fullPath);
    }
  }
  return files;
}

async function processFile(filePath) {
  let content = readFileSync(filePath, 'utf-8');
  const styleRegex = /<style(\s[^>]*)?>([\s\S]*?)<\/style>/g;
  const matches = [...content.matchAll(styleRegex)];
  if (matches.length === 0) return;

  let hasChanges = false;

  for (const match of matches) {
    const [fullMatch, attrs, cssContent] = match;
    if (!cssContent.trim()) continue;

    // Preprocess @apply (and any other Tailwind/PostCSS features),
    // then fix dark mode selectors for Svelte compatibility.
    const processed = await postcss([
      tailwindcss({ config: join(PROJECT_ROOT, 'tailwind.config.js') }),
      autoprefixer,
      fixDarkModePlugin,
    ]).process(cssContent, { from: undefined });

    const replacement = `<style${attrs || ''}>${processed.css}</style>`;
    content = content.replace(fullMatch, replacement);
    hasChanges = true;
  }

  if (hasChanges) {
    writeFileSync(filePath, content, 'utf-8');
    console.log('  preprocessed:', filePath.replace(DIST_DIR, ''));
  }
}

async function main() {
  console.log('Preprocessing @apply in <style> blocks of dist/ .svelte files...');
  const files = findSvelteFiles(DIST_DIR);
  for (const file of files) {
    await processFile(file);
  }

  // Scope ALL utility-class rules in editor.css under
  // .rich-text-editor-container so they don't leak into the
  // consumer's app and clobber their own styles.
  // Component <style> blocks are NOT scoped here — they stay in
  // the .svelte files and the consumer's Svelte compiler will
  // add per-component hashes to prevent class name conflicts.
  if (existsSync(EDITOR_CSS)) {
    console.log('Scoping utility classes in editor.css to', SCOPE_SELECTOR, '...');
    const finalCss = readFileSync(EDITOR_CSS, 'utf-8');
    const scoped = await postcss([scopePlugin]).process(finalCss, { from: undefined });
    writeFileSync(EDITOR_CSS, scoped.css, 'utf-8');
    console.log('Scoped editor.css written.');
  }

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
